import type { Metadata, Viewport } from "next";
import { Space_Grotesk, Inter, JetBrains_Mono } from "next/font/google";
import "./globals.css";
import { SITE_URL } from "@/lib/site";

// 05 · Typography — three families, three jobs, no overlap.
const display = Space_Grotesk({
  subsets: ["latin"],
  weight: ["300", "600", "700"],
  variable: "--font-display",
  display: "swap",
});

const sans = Inter({
  subsets: ["latin"],
  weight: ["400", "500", "600"],
  variable: "--font-sans",
  display: "swap",
});

const mono = JetBrains_Mono({
  subsets: ["latin"],
  weight: ["400", "500"],
  variable: "--font-mono",
  display: "swap",
});

const TITLE = "CoGraph — Read your codebase like a metro map";
const DESCRIPTION =
  "CoGraph derives a call graph from your repository — every function a node, every call an edge — and opens it beside your code in VS Code. Parsed from the syntax tree, never generated by a model. Free and MIT-licensed for Python, TypeScript, JavaScript, Java and C++.";

export const metadata: Metadata = {
  metadataBase: new URL(SITE_URL),
  title: TITLE,
  description: DESCRIPTION,
  alternates: { canonical: "/" },
  keywords: [
    "call graph",
    "code comprehension",
    "code review",
    "static analysis",
    "VS Code extension",
    "Python",
    "TypeScript",
    "JavaScript",
    "Java",
    "C++",
    "developer tools",
  ],
  openGraph: {
    title: TITLE,
    description:
      "Every function a node, every call an edge — derived from the syntax tree, beside your code in VS Code. Free and open source.",
    url: SITE_URL,
    siteName: "CoGraph",
    type: "website",
    locale: "en_US",
  },
  twitter: {
    card: "summary_large_image",
    title: TITLE,
    description:
      "Every function a node, every call an edge — derived from the syntax tree, beside your code in VS Code.",
  },
};

export const viewport: Viewport = {
  themeColor: "#0b0f14",
  colorScheme: "dark",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html
      lang="en"
      className={`${display.variable} ${sans.variable} ${mono.variable}`}
    >
      <body className="bg-ground font-sans text-ink-soft antialiased">
        {children}
      </body>
    </html>
  );
}
